### ISSUE TITLE
Hex type (`\h`) and nonhex type (`\H`) not implemented 

### ISSUE THREAD

**Issue by backus** [ammar/regexp_parser#21]
```ruby
2.3.0 :012 > Regexp::Parser.parse(/\h/)
Regexp::Syntax::NotImplementedError: Regexp::Syntax::Ruby::V230 does not implement: [type:hex]
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/syntax.rb:154:in `implements!'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/lexer.rb:22:in `block in lex'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/scanner.rb:4200:in `emit'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/scanner.rb:3366:in `scan'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/lexer.rb:20:in `lex'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/parser.rb:26:in `parse'
	from (irb):12
	from /Users/johnbackus/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'

2.3.0 :013 > Regexp::Parser.parse(/\H/)
Regexp::Syntax::NotImplementedError: Regexp::Syntax::Ruby::V230 does not implement: [type:nonhex]
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/syntax.rb:154:in `implements!'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/lexer.rb:22:in `block in lex'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/scanner.rb:4200:in `emit'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/scanner.rb:3367:in `scan'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/lexer.rb:20:in `lex'
	from /Users/johnbackus/.rvm/gems/ruby-2.3.0/gems/regexp_parser-0.3.3/lib/regexp_parser/parser.rb:26:in `parse'
	from (irb):13
	from /Users/johnbackus/.rvm/rubies/ruby-2.3.0/bin/irb:11:in `<main>'
```

**Comment by ammar** [comment]
@backus I'm very sorry for the delayed response on all the previous issues. I've been slammed at work and I totally dropped the ball.

Hard to believe this has been around for that long (1.9.1). The Hex tokens are being added under `:escape` instead of `:type`:

https://github.com/ammar/regexp_parser/blob/master/lib/regexp_parser/syntax/ruby/1.9.1.rb#L18

I will push a fix shortly.
